image: microsoft/dotnet:2.0.6-sdk-2.1.101-stretch

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build src/TicTacToe
          - dotnet test tests/TicTacToe.Tests