
module TicTacToe.Dialog

let Greeting = "Let's play TicTacToe!"
let SelectLang = "Please select a language."
let SelectPlayerType = "Choose computer or human player."
let SelectDifficulty = "Select the computer difficulty."
let PTypeHuman = "1 - Human"
let PTypeComputer = "2 - Computer"
let PickBoardSize = "Select the board size."
let TurnPrompt = "It's your turn."
let MoveEntryPrompt = "Enter the number of an open space."
let ComputerThinking = "The computer is thiking."
let Player1Announce = "Player 1 it is your turn."
let Player2Announce = "Player 2 it is your turn."
let Player1Win = "Player 1 is the winner!"
let Player2Win = "Player 2 is the winner!"
let ComputerAnnounce = "It is the computers turn."
let GameOver = "Game Over"
let Win = "You have won the game!"
let Tie = "The game is a tie."
let InputPrompt = "Please input the number of an open space."
let ContinuePlaying = "Do you want to play again? Input [y] for yes, [n] to exit"
let Easy = "easy"
let Medium = "medium"
let Hard = "hard"
let GameOptions = "1 - Computer Vs Computer\n2 - Human Vs Computer\n3 - Human Vs Human"
let VerticalPadding = "\n\n\n\n"
