
module TicTacToe.Dialog

let Greeting = "Let's play TicTacToe!"
let SelectLang = "Please select a language."
let SelectGameType = "Select the game type."
let SelectDifficulty = "Select the difficulty of player "
let DifficultyOptions = "1 - Easy (random) \n2 - Medium (limited look-ahead)\n3 - Hard (unbeatable)"
let PTypeHuman = "1 - Human"
let PTypeComputer = "2 - Computer"
let PickBoardSize = "Select the board size."
let TurnPrompt = "It's your turn."
let MoveEntryPrompt = "Enter the number of an open space."
let ComputerThinking = "The computer is thinking."
let Player1Announce = "Player 1 it is your turn."
let Player2Announce = "Player 2 it is your turn."
let Player1Win = "Player 1 is the winner!"
let Player2Win = "Player 2 is the winner!"
let ComputerAnnounce = "It is the computer's turn."
let GameOver = "Game Over"
let Win = "You have won the game!"
let Tie = "The game is a tie."
let InputPrompt = "Please input the number of an open space."
let ContinuePlaying = "Do you want to play again? Input [y] for yes, [n] to exit"
let GameOptions = "1 - Computer Vs Computer\n2 - Human Vs Computer\n3 - Human Vs Human"
let VerticalPadding = "\n\n\n\n"
let NewLine = "\n"
